version: "3.8"

services:
  db:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

# POSTGRES_DB é o mesmo nome do POSTGRES_USER